name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: easytax-frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./easytax-frontend
      run: npm ci
        
    - name: Build with UTF-8 encoding
      working-directory: ./easytax-frontend
      run: |
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
        npm run build
        
    - name: Add .nojekyll file
      run: |
        touch ./easytax-frontend/out/.nojekyll
        echo "Created .nojekyll file to disable Jekyll processing"
        
    - name: Verify build output
      run: |
        ls -la ./easytax-frontend/out/
        head -20 ./easytax-frontend/out/index.html
        echo "Checking for .nojekyll file:"
        ls -la ./easytax-frontend/out/.nojekyll
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './easytax-frontend/out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
